"""
generator_agent.py
═══════════════════════════════════════════════════════════════════════════════
PURPOSE
───────
Step 3 of the pipeline.  Receives the structured parsed_pages dict from
planner_agent.py and produces two kinds of output:

  1. Page Object files  (output/pages/<PageName>.js)
     One file per unique page.  Each file is a JavaScript ES module exporting
     a class with async methods that wrap the Playwright locators captured from
     the real DOM.  The LLM writes these — one focused call per file.

  2. A deterministic test spec  (output/tests/alltest.spec.js)
     This file is assembled entirely in Python from the parsed plan — NO LLM
     involvement.  This guarantees:
       • no duplicate imports
       • no wrong page variable names
       • no invented method calls
       • correct navigation order

This module is self-contained.  It exposes ONE public entry point:

    from generator_agent import run_generator_agent

    state: PipelineState = run_generator_agent(state)

The return value is an updated copy of state with:

    state["generated_files"]  – dict: rel_path → code string
    state["errors"]           – list[str] any non-fatal error messages

OUTPUT FILES (written to output/)
──────────────────────────────────
  output/pages/<ClassName>.js        – one per unique page
  output/tests/alltest.spec.js       – single end-to-end spec

PAGE OBJECT CONTRACT
─────────────────────
Every generated Page Object follows this exact structure:

    import { expect } from '@playwright/test';   // expect ONLY — never test

    export default class LoginPage {
      constructor(page) {
        this.page = page;   // page stored as instance var — never as method arg
      }

      async enterEmail(value) {
        await this.page.getByLabel("Email").fill(value);
      }

      async clickLogin() {
        await this.page.getByRole("button", { name: "Login" }).click();
      }

      async verifyLoginPage() {
        await expect(this.page.getByRole("heading", { name: "Login" })).toBeVisible();
      }
    }

DESIGN NOTES
────────────
• Each Page Object is generated by a single LLM call with exact method
  contracts as input — the LLM fills in the implementation, not the interface.
• The spec file is assembled by Python string manipulation — no LLM.
• Methods containing enter/fill/set/input/type in their name receive a
  `(value)` parameter and are called with 'test_value' in the spec.
• All other methods receive no parameters.
• Markdown fences in LLM output are stripped before writing to disk.
"""

from __future__ import annotations

import os
import re
from typing import TYPE_CHECKING

from dotenv import load_dotenv
from langchain_groq import ChatGroq
from llm_utils import invoke_llm_with_retry

load_dotenv()

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────────────────
BASE_URL   = "https://rahulshettyacademy.com/client/#/auth/login"
OUTPUT_DIR = "output"

# Default test credentials
DEFAULT_EMAIL = "harsh.yadav262002@gmail.com"
DEFAULT_PASSWORD = "Harsh@123"

os.makedirs(f"{OUTPUT_DIR}/pages", exist_ok=True)
os.makedirs(f"{OUTPUT_DIR}/tests", exist_ok=True)

_llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
    groq_api_key=os.getenv("GROQ_API_KEY"),
)

if TYPE_CHECKING:
    from pipeline import PipelineState


# ─────────────────────────────────────────────────────────────────────────────
# RATE LIMIT RESILIENCE
# ─────────────────────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────────────────────
# PLAYWRIGHT SYNTAX REFERENCE
# Read once at module load.  Injected into every LLM prompt so the model
# always has the correct .first / .nth() / await / expect() syntax in context.
# The reference file lives next to generator_agent.py (or OUTPUT_DIR parent).
# ─────────────────────────────────────────────────────────────────────────────
_REFERENCE_PATHS = [
    os.path.join(os.path.dirname(__file__), "playwright_syntax_reference.md"),
    "playwright_syntax_reference.md",
    os.path.join("..", "playwright_syntax_reference.md"),
]

_SYNTAX_REFERENCE: str = ""
for _ref_path in _REFERENCE_PATHS:
    if os.path.exists(_ref_path):
        _SYNTAX_REFERENCE = open(_ref_path, encoding="utf-8").read()
        print(f"[GeneratorAgent]  📖  Loaded syntax reference from {_ref_path}")
        break

if not _SYNTAX_REFERENCE:
    # Fallback: embed the critical rules inline so generation still works
    _SYNTAX_REFERENCE = """
## CRITICAL PLAYWRIGHT SYNTAX RULES

### .first is a PROPERTY — never call it as .first()
CORRECT:   await this.page.getByPlaceholder("search").first.fill(value);
WRONG:     await this.page.getByPlaceholder("search").first().fill(value);

### .nth() is a METHOD — always has parentheses
CORRECT:   await this.page.locator(".card").nth(0).click();
WRONG:     await this.page.locator(".card").nth.click();

### Every Playwright action needs await
CORRECT:   await this.page.getByRole("button", { name: "Login" }).click();
WRONG:     this.page.getByRole("button", { name: "Login" }).click();

### Assertions use expect() wrapping the locator
CORRECT:   await expect(this.page.getByRole("heading")).toBeVisible();
WRONG:     await this.page.getByRole("heading").toBeVisible();

### Locator methods (.getByRole etc.) do NOT need await — they return a Locator synchronously
CORRECT:   const loc = this.page.getByLabel("Email");
WRONG:     const loc = await this.page.getByLabel("Email");

### Strict mode — use .first when a locator might match multiple elements
await this.page.getByPlaceholder("search").first.fill(value);
await this.page.locator(".card", { hasText: "ADIDAS" }).getByRole("button").click();
"""
    print("[GeneratorAgent]  ⚠️   playwright_syntax_reference.md not found — using inline fallback")


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 1 – HELPERS
# ═════════════════════════════════════════════════════════════════════════════

def _camel(pascal: str) -> str:
    """Convert a PascalCase class name to a camelCase variable name.
    Example: "LoginPage" → "loginPage"
    """
    return pascal[0].lower() + pascal[1:] if pascal else pascal


def _get_test_value(method_name: str) -> str:
    """
    Return the appropriate test value based on the method name.
    - Methods containing 'email' or 'username' → use DEFAULT_EMAIL
    - Methods containing 'password' or 'pwd' → use DEFAULT_PASSWORD
    - All others → use generic 'test_value'
    """
    method_lower = method_name.lower()
    if "email" in method_lower or "username" in method_lower:
        return f"'{DEFAULT_EMAIL}'"
    elif "password" in method_lower or "pwd" in method_lower:
        return f"'{DEFAULT_PASSWORD}'"
    else:
        return "'test_value'"


def _strip_markdown_fences(code: str) -> str:
    """
    Remove ```javascript / ```js / ``` fences that the LLM might wrap its
    output in even when instructed not to.  Leaves the raw code content.
    """
    code = re.sub(r"^```(?:javascript|js)?\n?", "", code, flags=re.MULTILINE)
    code = re.sub(r"\n?```\s*$",                "",  code, flags=re.MULTILINE)
    return code.strip()


def _fix_strict_mode(code: str) -> str:
    """
    Post-process LLM-generated Page Object code before writing to disk.

    THE ROOT CAUSE we discovered:
        .first is a Locator property in Playwright >= 1.14.
        On ANY version mismatch, or when the LLM writes .first incorrectly,
        you get: TypeError: .first.fill is not a function

    THE PERMANENT FIX — never use .first or .last at all:
        .nth(0)  is a METHOD with parentheses, works on every Playwright version.
        .nth(-1) replaces .last.

    This function converts ALL .first/.last patterns to .nth() and
    adds .nth(0) before unguarded .click() and .fill() calls.
    """
    # ── Pass 1: .first.<action> → .nth(0).<action>  (property chain style)
    code = re.sub(
        r'\.first\.(click|fill|type|hover|check|uncheck|press|clear|selectOption)',
        r'.nth(0).\1', code
    )

    # ── Pass 2: .first().<action> → .nth(0).<action>  (old method-call style)
    code = re.sub(
        r'\.first\(\)\.(click|fill|type|hover|check|uncheck|press|clear|selectOption)',
        r'.nth(0).\1', code
    )

    # ── Pass 3: any remaining .first() → .nth(0)
    code = re.sub(r'\.first\(\)', '.nth(0)', code)

    # ── Pass 4: any remaining bare .first → .nth(0)
    code = re.sub(r'\.first\b', '.nth(0)', code)

    # ── Pass 5: .last variants → .nth(-1)
    code = re.sub(
        r'\.last\.(click|fill|type|hover|check|uncheck|press|clear|selectOption)',
        r'.nth(-1).\1', code
    )
    code = re.sub(r'\.last\(\)\.', '.nth(-1).', code)
    code = re.sub(r'\.last\b', '.nth(-1)', code)

    # ── Pass 6: line-by-line — add .nth(0) before bare .click()/.fill()
    fixed_lines = []
    for line in code.splitlines():
        stripped = line.strip()
        indent   = len(line) - len(line.lstrip())
        pad      = " " * indent

        if not stripped or stripped.startswith("//") or stripped.startswith("*"):
            fixed_lines.append(line)
            continue

        # Add .nth(0) before .click() when no scope guard present
        if ".click(" in line and "this.page." in line and "expect(" not in line:
            if ".nth(" not in line:
                line = line.replace(".click(", ".nth(0).click(")

        # Add .nth(0) before .fill() when no scope guard present
        if ".fill(" in line and "this.page." in line and "expect(" not in line:
            if ".nth(" not in line:
                line = line.replace(".fill(", ".nth(0).fill(")

        # ── Pass 7: ensure await on action lines (not inside expect)
        s = line.strip()
        if ("this.page." in s
                and "await" not in s
                and "expect(" not in s
                and not s.startswith("//")):
            line = pad + "await " + s

        fixed_lines.append(line)

    return "\n".join(fixed_lines)


def _validate_generated_js(code: str, file_name: str) -> list[str]:
    """
    Quick sanity check on generated JavaScript before writing to disk.
    Returns a list of error strings (empty = clean).

    Checks:
      - No .first() remaining (property called as function)
      - No .last()  remaining
      - import { expect } present
      - export default class present
      - No bare `page.` (without this.) in method bodies
    """
    issues = []
    # .first and .last in any form — use .nth(0) / .nth(-1) instead
    if re.search(r"\.first", code):
        issues.append(f"{file_name}: .first found — use .nth(0) instead (works on all Playwright versions)")
    if re.search(r"\.last", code):
        issues.append(f"{file_name}: .last found — use .nth(-1) instead")
    if "import { expect }" not in code:
        issues.append(f"{file_name}: missing import {{ expect }}")
    if "export default class" not in code:
        issues.append(f"{file_name}: missing export default class")
    # Bare page. in method body (not this.page, not in a comment)
    for line in code.splitlines():
        s = line.strip()
        if re.search(r'(?<![.\w])page\.\w+\(', s) and "this.page" not in s and not s.startswith("//"):
            issues.append(f"{file_name}: bare `page.` call (should be `this.page.`): {s[:80]}")
    return issues
    """
    Determine whether a method should accept a `value` parameter.
    Triggers if the method name starts with a fill/input verb OR the
    description contains fill/enter.
    """
    name_triggers = re.search(
        r"^(enter|fill|set|input|type)", method_name, re.IGNORECASE
    )
    desc_triggers = re.search(
        r"\b(fill|enter|type|input)\b", description or "", re.IGNORECASE
    )
    return bool(name_triggers or desc_triggers)


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 2 – PAGE OBJECT GENERATOR  (one LLM call per page)
# ═════════════════════════════════════════════════════════════════════════════

def _method_needs_param(method_name: str, description: str) -> bool:
    """
    Return True if this method should accept a `value` parameter.
    credential use email:harsh.yadav262002@gmail.com and password:Harsh@123
    Triggered when the method name starts with an input verb (enter/fill/set/
    input/type) OR the description explicitly mentions filling/entering a value.

    Examples:
        enterEmail()      → True   (name starts with "enter")
        fillSearchBox()   → True   (name starts with "fill")
        clickLogin()      → False
        verifyPage()      → False
    """
    name_triggers = re.search(
        r"^(enter|fill|set|input|type)", method_name, re.IGNORECASE
    )
    desc_triggers = re.search(
        r"\b(fill|enter|type|input)\b", description or "", re.IGNORECASE
    )
    return bool(name_triggers or desc_triggers)


def _generate_page_object(page_name: str, pg: dict) -> str:
    """
    Ask the LLM to write a Playwright Page Object class for a single page.

    The prompt provides:
      • The exact class name and file name
      • The exact import structure required
      • A METHOD CONTRACT for every method — type, locator, description
      • Absolute rules that prevent the most common LLM errors

    Returns the cleaned JavaScript code string (no markdown fences).
    """
    class_name = pg["class_name"]
    file_name  = pg["file_name"]
    methods    = pg["methods"]

    # Build method contracts (one per method, clearly formatted)
    contract_lines: list[str] = []
    for m in methods:
        has_param = _method_needs_param(m["method_name"], m.get("description", ""))
        param_sig = "(value)" if has_param else "()"
        contract_lines.append(
            f"  METHOD: async {m['method_name']}{param_sig}\n"
            f"    type        : {m['type']}\n"
            f"    locator     : {m['locator']}\n"
            f"    description : {m['description']}\n"
            f"    navigates_to: {m['navigates_to'] or 'none'}"
        )

    all_contracts = "\n\n".join(contract_lines)

    # Build failure context from previous test run (empty on first attempt)
    prior_failures = pg.get("_test_failures", [])
    failure_context = (
        "None — this is the first generation attempt."
        if not prior_failures
        else "\n".join(
            f"  - [{f['error_type']}] {f['error_msg'][:300]}"
            for f in prior_failures
        )
    )

    prompt = f"""You are a Playwright Page Object Model expert.
Generate a JavaScript Page Object file using ONLY the syntax shown in the
PLAYWRIGHT SYNTAX REFERENCE below.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PLAYWRIGHT SYNTAX REFERENCE  (authoritative — follow exactly)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{_SYNTAX_REFERENCE}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FILE TO GENERATE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
File  : pages/{file_name}
Class : {class_name}

Required file structure:

import {{ expect }} from '@playwright/test';

export default class {class_name} {{
  constructor(page) {{
    this.page = page;
  }}
  // methods below
}}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NON-NEGOTIABLE RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
R1. import {{ expect }} ONLY — NEVER import {{ test }}
R2. Every method → async
R3. Every Playwright action call (.click, .fill, .type, .hover) → preceded by await
R4. Use this.page everywhere — NEVER accept `page` as a method parameter
R5. Validation (TYPE=validation): await expect(this.page.<locator>).toBeVisible()
R6. Action     (TYPE=action):     await this.page.<locator>.click()
                                  await this.page.<locator>.fill(value)

R7. STRICT MODE — when a locator may match multiple elements:
    • ALWAYS use .nth(0) — it is a METHOD with parentheses, works on ALL Playwright versions:
        await this.page.getByPlaceholder("search").nth(0).fill(value);
        await this.page.getByRole("button", {{ name: "Add" }}).nth(0).click();
    • For a specific card scope:
        await this.page.locator(".card").nth(0).getByRole("button").click();
        await this.page.locator(".card", {{ hasText: "ADIDAS" }}).getByRole("button").click();

R8. NEVER use .first or .last — they cause TypeError on many Playwright versions.
    ALWAYS use .nth(0) for first element, .nth(-1) for last element.
R9. Use ONLY locators from METHOD CONTRACTS below — do not invent any
R10. NO_LOCATOR placeholder → write: // TODO: locator not captured

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
METHOD CONTRACTS — implement each method exactly as specified
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{all_contracts}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PREVIOUS TEST RUN FAILURES (fix these in the generated code)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{failure_context}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT: JavaScript only. No markdown fences. Start with the import line."""

    raw = invoke_llm_with_retry(_llm, prompt)
    raw = _strip_markdown_fences(raw)
    fixed = _fix_strict_mode(raw)

    # Post-generation validation — catch anything _fix_strict_mode missed
    issues = _validate_generated_js(fixed, file_name)
    if issues:
        print(f"     ⚠️  Post-gen issues detected — applying emergency fixes:")
        for issue in issues:
            print(f"        🔴  {issue}")
        # Emergency nuclear pass: remove ALL () after .first and .last
        fixed = re.sub(r'\.(first|last)\(\)', r'.\1', fixed)
        # Re-validate
        remaining = _validate_generated_js(fixed, file_name)
        if remaining:
            print(f"     ❌  Could not auto-fix: {remaining}")
        else:
            print(f"     ✅  Emergency fixes applied successfully")

    return fixed


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 3 – SPEC FILE ASSEMBLER  (zero LLM — deterministic Python)
#
#  Why no LLM here?  The LLM cannot see the full list of generated Page Object
#  files and tends to:
#    - duplicate imports
#    - use wrong variable names
#    - invent method calls not in the plan
#
#  Python can assemble this perfectly from the parsed_pages dict.
# ═════════════════════════════════════════════════════════════════════════════

def _assemble_spec(parsed_pages: dict) -> str:
    """
    Assemble a Playwright test spec from the parsed plan.

    Structure of the generated spec:

        import { test, expect } from '@playwright/test';
        import LoginPage       from '../pages/LoginPage.js';
        import DashboardPage   from '../pages/DashboardPage.js';

        test('end-to-end test', async ({ page }) => {
          const loginPage     = new LoginPage(page);
          const dashboardPage = new DashboardPage(page);

          await page.goto('<BASE_URL>');

          // ── Login Page ──
          await loginPage.enterEmail('harsh.yadav262002@gmail.com');
          await loginPage.enterPassword('Harsh@123');
          await loginPage.clickLogin();
          // → navigated to: Dashboard Page

          // ── Dashboard Page ──
          await dashboardPage.verifyDashboardPage();
          await dashboardPage.clickProduct();
          ...
        });

    Returns the complete spec file content as a string.
    """
    unique_pages = list(parsed_pages.values())   # OrderedDict — visit order preserved

    # 1. Import block
    import_lines = ["import { test, expect } from '@playwright/test';"]
    for pg in unique_pages:
        import_lines.append(
            f"import {pg['class_name']} from '../pages/{pg['file_name']}';"
        )

    # 2. Instantiation block (inside test body)
    inst_lines: list[str] = []
    for pg in unique_pages:
        var_name = _camel(pg["class_name"])
        inst_lines.append(
            f"  const {var_name} = new {pg['class_name']}(page);"
        )

    # 3. Test body — walk pages in visit order, call each method once
    body_lines: list[str] = [
        f"  await page.goto('{BASE_URL}');",
    ]

    for pg in unique_pages:
        var_name = _camel(pg["class_name"])
        body_lines.append(f"\n  // ── {pg['page_name']} ──")

        for m in pg["methods"]:
            mname = m["method_name"]
            if _method_needs_param(mname, m.get("description", "")):
                test_value = _get_test_value(mname)
                body_lines.append(f"  await {var_name}.{mname}({test_value});")
            else:
                # .first is already added inside page object methods
                body_lines.append(f"  await {var_name}.{mname}();")

            if m["navigates_to"]:
                body_lines.append(f"  // → navigated to: {m['navigates_to']}")

    # 4. Assemble full file
    spec_parts = [
        "\n".join(import_lines),
        "\n",
        "test('end-to-end test', async ({ page }) => {",
        "\n".join(inst_lines),
        "\n".join(body_lines),
        "});",
    ]

    return "\n".join(spec_parts) + "\n"


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 4 – FILE WRITER
# ═════════════════════════════════════════════════════════════════════════════

def _write_files(generated: dict[str, str]) -> None:
    """
    Write all generated files to disk under OUTPUT_DIR.

    generated dict format:
        {
            "pages/LoginPage.js":       "import { expect } from ...",
            "tests/alltest.spec.js":    "import { test, expect } from ...",
        }
    """
    print(f"\n📁  Writing output files...")
    for rel_path, code in generated.items():
        full_path = os.path.join(OUTPUT_DIR, rel_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"   📄  {full_path}  ({len(code.splitlines())} lines)")


# ═════════════════════════════════════════════════════════════════════════════
#  PUBLIC API  —  this is the only function the pipeline imports
# ═════════════════════════════════════════════════════════════════════════════

def run_generator_agent(state: "PipelineState") -> "PipelineState":
    """
    LangGraph node function.  Receives pipeline state with parsed_pages
    populated by planner_agent.  Generates all Page Object files and the
    test spec, writes them to disk, and returns updated state.

    Mutates (returns updated copy of):
        state["generated_files"]   – dict of rel_path → code
        state["errors"]            – list[str]
    """
    print(f'\n{"=" * 60}\n  NODE 3 / GENERATOR AGENT\n{"=" * 60}')

    parsed_pages: dict = state["parsed_pages"]
    errors = list(state.get("errors", []))

    if not parsed_pages:
        errors.append("GeneratorAgent: skipped — parsed_pages is empty (PlannerAgent failed?)")
        return {**state, "generated_files": {}, "errors": errors}

    # Inject test failures into page dicts so the LLM can fix them
    test_result = state.get("test_run_result", {})
    all_failures = test_result.get("failures", [])
    for page_name, pg in parsed_pages.items():
        class_name = pg.get("class_name","")
        # Match failures to this page object by checking if class_name appears in location
        relevant = [f for f in all_failures if class_name.lower() in f.get("location","").lower()
                    or class_name.lower() in f.get("error_msg","").lower()]
        pg["_test_failures"] = relevant
        if relevant:
            print(f"  ⚠️  Injecting {len(relevant)} failure(s) into {class_name} regeneration")

    generated: dict[str, str] = {}

    # ── Generate one Page Object per unique page ──────────────────────────
    for page_name, pg in parsed_pages.items():
        print(f"\n  🔧  {pg['file_name']} ...")
        code = _generate_page_object(page_name, pg)
        generated[f"pages/{pg['file_name']}"] = code
        print(f"     ✅  {len(code.splitlines())} lines")

    # ── Assemble spec deterministically (no LLM) ─────────────────────────
    print(f"\n  🔧  tests/alltest.spec.js ...")
    spec = _assemble_spec(parsed_pages)
    generated["tests/alltest.spec.js"] = spec
    print(f"     ✅  {len(spec.splitlines())} lines")

    # ── Write to disk ─────────────────────────────────────────────────────
    _write_files(generated)

    return {**state, "generated_files": generated, "errors": errors}